/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface HomePage {}
  interface MyApp {}
  interface Page1 {
    'dataFromServer': string;
    'first': string;
    'initialCount': number;
    'last': string;
    'todos': string;
  }
  interface Page2 {}
}

declare global {


  interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {}
  var HTMLHomePageElement: {
    prototype: HTMLHomePageElement;
    new (): HTMLHomePageElement;
  };

  interface HTMLMyAppElement extends Components.MyApp, HTMLStencilElement {}
  var HTMLMyAppElement: {
    prototype: HTMLMyAppElement;
    new (): HTMLMyAppElement;
  };

  interface HTMLPage1Element extends Components.Page1, HTMLStencilElement {}
  var HTMLPage1Element: {
    prototype: HTMLPage1Element;
    new (): HTMLPage1Element;
  };

  interface HTMLPage2Element extends Components.Page2, HTMLStencilElement {}
  var HTMLPage2Element: {
    prototype: HTMLPage2Element;
    new (): HTMLPage2Element;
  };
  interface HTMLElementTagNameMap {
    'home-page': HTMLHomePageElement;
    'my-app': HTMLMyAppElement;
    'page-1': HTMLPage1Element;
    'page-2': HTMLPage2Element;
  }
}

declare namespace LocalJSX {
  interface HomePage {}
  interface MyApp {}
  interface Page1 {
    'dataFromServer'?: string;
    'first'?: string;
    'initialCount'?: number;
    'last'?: string;
    'todos'?: string;
  }
  interface Page2 {}

  interface IntrinsicElements {
    'home-page': HomePage;
    'my-app': MyApp;
    'page-1': Page1;
    'page-2': Page2;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'home-page': LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
      'my-app': LocalJSX.MyApp & JSXBase.HTMLAttributes<HTMLMyAppElement>;
      'page-1': LocalJSX.Page1 & JSXBase.HTMLAttributes<HTMLPage1Element>;
      'page-2': LocalJSX.Page2 & JSXBase.HTMLAttributes<HTMLPage2Element>;
    }
  }
}


